#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from rclpy.context import Context
from std_msgs.msg import String
from geometry_msgs.msg import PoseStamped

def main():
    tester= Pub()
    tester.process()

class StringCallBack():
    def __init__(self, pub, msg):
        self._publisher= pub
        self._msg= String()
        self._msg.data= msg

    def __call__(self):
        self._publisher.publish( self._msg )

class PoseCallBack():
    def __init__(self, pub, msg):
        self._publisher= pub
        self._msg= PoseStamped()
        self._msg= msg

    def __call__(self):
        self._publisher.publish( self._msg )

class Pub():
    def __init__(self):
        pass

    def process(self):
        # Ros initialization
        rclpy.init()
        executor= rclpy.get_global_executor()

        self._nodes= []
        self._test_publishers= []

        '''
            response.message = "-5.3 0.84 0.0"
            (-2.95, 1.51) chemin A
            (-0.5 -2.15) chemin B
        '''

        for domId, msg, freq, topic in zip( [28, 44], ["-2.95 1.51 0.0", "-0.5 -2.15 0.0"], [2.0, 0.3], ['goal','goal_pose'] ) :

            # goal -> turtle_bot
            # goal_pose -> Bbot
            
            # Construct context
            rosContext = Context()
            rosContext.init(domain_id= domId)
            node= Node( f"multipub{domId}", context=rosContext )
            
            # Pose 
            pointTab = msg.split(" ")
            point = PoseStamped()

            point.header.stamp = node.get_clock().now().to_msg()
            point.header.frame_id = "map" 


            point.pose.position.x = float(pointTab[0])
            point.pose.position.y = float(pointTab[1])
            point.pose.position.z = float(pointTab[2])

            point.pose.orientation.x = 0.0
            point.pose.orientation.y = 0.0
            point.pose.orientation.z = 0.0
            point.pose.orientation.w = 1.0

            # Publisher
            publisher= node.create_publisher( PoseStamped, topic, 10 )
            node.create_timer( freq, PoseCallBack( publisher, point ) )

            executor.add_node( node )
            self._nodes.append( node )

        # Infinite loop:
        executor.spin()

        # Clean stop:
        for node in self._nodes :
            node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
