#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import PointStamped
import yaml
import os
from datetime import datetime


class ROSListener(Node):

    def __init__(self):
        super().__init__('listener_new_point')

        # Déclaration des paramètres
        self.declare_parameter('output_file', 'points.yaml')
        self.declare_parameter('append', True)
        self.declare_parameter('Arrival', False)
        self.declare_parameter('Deposit', False)
        #Rajouter un truc pour modifier le point avec un modify et va chercher l'id pour le modifier (à voir si je peux le faire)
        #Maybe pouvoir le supprimer

        self.output_file = self.get_parameter('output_file').value
        self.append = self.get_parameter('append').value

        self.get_logger().info(f"Écriture YAML : {self.output_file}")
        self.get_logger().info(f"Mode append : {self.append}")

        self.subscription = self.create_subscription(
            PointStamped,
            '/clicked_point',
            self.listener_callback,
            10
        )

        # Initialisation du fichier si nécessaire
        if not self.append or not os.path.exists(self.output_file):
            with open(self.output_file, 'w') as f:
                yaml.dump({'points': []}, f)

    def listener_callback(self, msg: PointStamped):
        if self.get_parameter('Arrival').value == True:
            point_data = {
                'id': 'Arrival.' + str(msg.header.stamp.sec) + str(msg.header.stamp.nanosec),
                'x': msg.point.x,
                'y': msg.point.y,
                'z': f"{msg.point.z:.2f}"
            }
            self.save_to_yaml(point_data)
            self.get_logger().info(f"Point sauvegardé : {point_data}")
        elif self.get_parameter('Deposit').value == True:
            point_data = {
                'id': 'Deposit.' + str(msg.header.stamp.sec) + str(msg.header.stamp.nanosec),
                'x': msg.point.x,
                'y': msg.point.y,
                'z': f"{msg.point.z:.2f}"
            }
            self.save_to_yaml(point_data)
            self.get_logger().info(f"Point sauvegardé : {point_data}")

    def save_to_yaml(self, point_data):
        with open(self.output_file, 'r') as f:
            data = yaml.safe_load(f) or {'points': []}

        data['points'].append(point_data)

        with open(self.output_file, 'w') as f:
            yaml.dump(data, f, default_flow_style=False)


def main():
    rclpy.init()
    node = ROSListener()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()

'''
ros2 run mon_package listener_yaml \
  --ros-args \
  -p output_file:=/tmp/points.yaml \
  -p append:=true

  '''
