#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from rclpy.action import ActionClient

from nav2_msgs.action import ComputePathToPose, NavigateToPose
from geometry_msgs.msg import PoseStamped

from tf2_ros import Buffer, TransformListener, LookupException, ConnectivityException, ExtrapolationException
from multi_robot_larm.msg import Bid, Package, Pose

import os

class Nav2PathEvaluator(Node):

    # Initialize node, action clients, publishers, subscribers, and timers.
    def __init__(self):
        
        super().__init__('nav2_path_evaluator')

        self.path_client = ActionClient(
            self,
            ComputePathToPose,
            'compute_path_to_pose'
        )

        self.nav_client = ActionClient(self, NavigateToPose, 'navigate_to_pose')
        self.tf_buffer = Buffer()
        self.tf_listener = TransformListener(self.tf_buffer, self)

        self.subscription = self.create_subscription(
            Package,
            '/start_bid',
            self.listener_callback,
            10
        )

        self.subscription_win_bid = self.create_subscription(
            Package,
            '/win_bid',
            self.listener_win_bid_callback,
            10
        )
        # Publisher de distance
        self.distance_pub = self.create_publisher(
            Bid,
            '/bid',
            10
        )

        self.pose_pub = self.create_publisher(
            Pose,
            '/robot_pose',
            10
        )

        # Publish at 10 Hz
        self.pose_timer = self.create_timer(0.1, self.publish_robot_pose)

        self.id_colis = -1
        self.waiting_list = []
        self.path_list = []
        self.iteration = 0
        self.distance = 0.0
        self.current_goal = None
        self.send_goal()

    # Publish current robot pose using TF map → base_link transform.
    def publish_robot_pose(self):
        
        try:
            transform = self.tf_buffer.lookup_transform(
                'map',          # target frame
                'base_link',    # source frame (or 'base_footprint')
                rclpy.time.Time()
            )

            pose = PoseStamped()
            pose.header.stamp = self.get_clock().now().to_msg()
            pose.header.frame_id = 'map'

            pose.pose.position.x = transform.transform.translation.x
            pose.pose.position.y = transform.transform.translation.y
            pose.pose.position.z = transform.transform.translation.z

            pose.pose.orientation = transform.transform.rotation

            msg = Pose()
            ros_domain_id = os.environ.get("ROS_DOMAIN_ID", "Non défini")
            msg.ros_domain_id = int(ros_domain_id) if ros_domain_id is not None else -1
            msg.pose = pose

            self.pose_pub.publish(msg)

        except (LookupException, ConnectivityException, ExtrapolationException):
            self.get_logger().warn('TF lookup failed for robot pose')
    
    # Wait for Nav2 action servers to be available.
    def send_goal(self):
        
        self.path_client.wait_for_server()
        self.nav_client.wait_for_server()

    # Handle planner goal acceptance and request path result.
    def path_response_callback(self, future):
        
        goal_handle = future.result()

        if not goal_handle.accepted:
            self.get_logger().error("Le planner a refusé la requête")
            return
        
        self.result_future = goal_handle.get_result_async()
        self.result_future.add_done_callback(self.path_result_callback)


    # Compute path length and publish bid once all segments are processed.
    def path_result_callback(self, future):
        result = future.result().result
        path = result.path

        distance = 0.0
        prev = None

        for pose in path.poses:
            x = pose.pose.position.x
            y = pose.pose.position.y

            if prev is not None:
                dx = x - prev[0]
                dy = y - prev[1]
                distance += (dx**2 + dy**2) ** 0.5

            prev = (x, y)

        self.distance += distance
        self.iteration += 1

        ros_domain_id = os.environ.get('ROS_DOMAIN_ID','Non défini')

        if self.iteration == len(self.waiting_list) + 2:
            msg = Bid()
            msg.id = self.id_colis
            msg.ros_domain_id = int(ros_domain_id)
            msg.cost = self.distance
            self.id_colis = -1
            self.get_logger().info(f"\n\nDistance totale estimée: {self.distance:.2f}")
            self.get_logger().info(f"Message envoyé: {msg}")
            self.iteration = 0
            self.distance_pub.publish(msg)
            self.distance = 0.0

    # Estimate total path cost for a new bid request.
    def listener_callback(self, msg: Package, nodeROS):
        
        self.id_colis = msg.id
        point1= msg.departure
        point2=msg.arrival

        pathList=[]

        #print(f"waiting_list : {self.waiting_list}")
        for i in range(len(self.waiting_list)):

            path=ComputePathToPose.Goal()
            path.goal = PoseStamped()
            path.start = PoseStamped()

            if i == 0:
                path.use_start = False
            else:
                path.start.pose.position.x = self.waiting_list[i-1].pose.position.x
                path.start.pose.position.y = self.waiting_list[i-1].pose.position.y
                path.start.pose.orientation.w = 1.0
                path.start.header.frame_id = 'map'
                path.start.header.stamp = self.get_clock().now().to_msg()

            path.goal.pose.position.x = self.waiting_list[i].pose.position.x
            path.goal.pose.position.y = self.waiting_list[i].pose.position.y
            path.goal.pose.orientation.w = 1.0
            path.goal.header.frame_id = 'map'
            path.goal.header.stamp = self.get_clock().now().to_msg()
            self.send_goal_future = self.path_client.send_goal_async(path)
            self.send_goal_future.add_done_callback(self.path_response_callback)


        path1=ComputePathToPose.Goal()
        
        
        if len(self.waiting_list) != 0:
            path1.start = PoseStamped()
            path1.use_start = True
            TMP = self.waiting_list[-1]
            path1.start.pose.position.x = self.waiting_list[-1].pose.position.x
            path1.start.pose.position.y = self.waiting_list[-1].pose.position.y
            path1.start.pose.orientation.w = 1.0
        else:
            path1.use_start = False

        path1.goal = PoseStamped()

        path1.goal.pose.position.x = point1.pose.position.x
        path1.goal.pose.position.y = point1.pose.position.y
        path1.goal.pose.orientation.w = 1.0
        pathList.append(path1)
        path2=ComputePathToPose.Goal()
        path2.use_start = True

        path2.start = PoseStamped()
        path2.goal = PoseStamped()

        path2.start.pose.position.x = point1.pose.position.x
        path2.start.pose.position.y = point1.pose.position.y
        path2.start.pose.orientation.w = 1.0

        path2.goal.pose.position.x = point2.pose.position.x
        path2.goal.pose.position.y = point2.pose.position.y
        path2.goal.pose.orientation.w = 1.0
        pathList.append(path2)

        for point in pathList:
            if point.use_start == True:
                point.start.header.frame_id = 'map'
                point.start.header.stamp = self.get_clock().now().to_msg()
            point.goal.header.frame_id = 'map'
            point.goal.header.stamp = self.get_clock().now().to_msg()
            self.send_goal_future = self.path_client.send_goal_async(point)
            self.send_goal_future.add_done_callback(self.path_response_callback)

    # Handle won bid and queue pickup and delivery points.
    def listener_win_bid_callback(self, msg):
        self.id_colis = msg.id
        point1 = msg.departure
        point2 = msg.arrival
        self.waiting_list.append(point1)
        self.waiting_list.append(point2)
        
        self.get_logger().info(f"[LISTENER WIN_BID] Points ajoutés : {msg}")
        
        if self.current_goal is None:
            self.send_navigation_goal(self.waiting_list[0])

    # Send a navigation goal to Nav2.
    def send_navigation_goal(self, point):
        goal_msg = NavigateToPose.Goal()
        goal_msg.pose.pose.position.x = point.pose.position.x
        goal_msg.pose.pose.position.y = point.pose.position.y
        goal_msg.pose.pose.orientation.w = 1.0
        goal_msg.pose.header.frame_id = 'map'
        goal_msg.pose.header.stamp = self.get_clock().now().to_msg()
        self.current_goal = point
        self.nav_client.send_goal_async(goal_msg).add_done_callback(self.nav_response_callback)
    
    # Check if navigation goal was accepted.
    def nav_response_callback(self, future):
        goal_handle = future.result()
        if not goal_handle.accepted:
            self.get_logger().warn("Navigation goal rejected")
            self.current_goal = None
            return
        goal_handle.get_result_async().add_done_callback(self.nav_result_callback)

    # Handle navigation result and send next goal if available.
    def nav_result_callback(self, future):
        result = future.result()
        status = result.status

        if status == 4:  # STATUS_SUCCEEDED
            self.get_logger().info("Robot arrivé à destination ✅")

            if self.waiting_list and self.waiting_list[0] == self.current_goal:
                self.waiting_list.pop(0)   # ✅ ICI ET SEULEMENT ICI

        else:
            self.get_logger().warn(f"Navigation échouée, status={status}")

        self.current_goal = None

        if self.waiting_list:
            self.send_navigation_goal(self.waiting_list[0])


# Initialize ROS node and spin.
def main(args=None):
    rclpy.init(args=args)
    node = Nav2PathEvaluator()
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == '__main__':
    main()
