#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from rclpy.action import ActionClient

from nav2_msgs.action import ComputePathToPose, NavigateToPose
from geometry_msgs.msg import PoseStamped

from tf2_ros import Buffer, TransformListener
from multi_robot_larm.msg import Bid, Package

import os


class Nav2PathEvaluator(Node):

    def __init__(self):
        super().__init__('nav2_path_evaluator')

        self.path_client = ActionClient(
            self,
            ComputePathToPose,
            'compute_path_to_pose'
        )

        self.nav_client = ActionClient(self, NavigateToPose, 'navigate_to_pose')
        self.tf_buffer = Buffer()
        self.tf_listener = TransformListener(self.tf_buffer, self)

        self.subscription = self.create_subscription(
            Package,
            '/start_bid',
            self.listener_callback,
            10
        )

        self.subscription_win_bid = self.create_subscription(
            Package,
            '/win_bid',
            self.listener_win_bid_callback,
            10
        )
        # Publisher de distance
        self.distance_pub = self.create_publisher(
            Bid,
            '/bid',
            10
        )
        self.id_colis = -1
        self.waiting_list = []
        self.path_list = []
        self.iteration = 0
        self.distance = 0.0
        self.current_goal = None
        self.send_goal()



    def send_goal(self):
        self.path_client.wait_for_server()
        self.nav_client.wait_for_server()


    def path_response_callback(self, future):
        goal_handle = future.result()

        if not goal_handle.accepted:
            self.get_logger().error("Le planner a refusé la requête")
            return

        #self.get_logger().info("Chemin accepté, attente du résultat")
        self.result_future = goal_handle.get_result_async()
        self.result_future.add_done_callback(self.path_result_callback)


    def path_result_callback(self, future):
        result = future.result().result
        path = result.path

        #self.get_logger().info(f"Nombre de points: {len(path.poses)}")

        distance = 0.0
        prev = None

        for pose in path.poses:
            x = pose.pose.position.x
            y = pose.pose.position.y

            if prev is not None:
                dx = x - prev[0]
                dy = y - prev[1]
                distance += (dx**2 + dy**2) ** 0.5

            prev = (x, y)

        #self.get_logger().info(f"Distance estimée: {distance:.2f} m")
        self.distance += distance
        self.iteration += 1
        #print(self.iteration)
        #print(self.distance)

        ros_domain_id = os.environ.get('ROS_DOMAIN_ID','Non défini')

        if self.iteration == len(self.waiting_list) + 2:
            msg = Bid()
            msg.id = self.id_colis
            msg.ros_domain_id = int(ros_domain_id)
            msg.cost = self.distance
            #msg.data = str(self.id_colis) + " " + str(ros_domain_id)  + " " +str(self.distance) #TODO get the ROS_DOMAIN_ID dynamicly
            self.id_colis = -1
            self.get_logger().info(f"Distance totale estimée: {self.distance:.2f}")
            self.get_logger().info(f"Message envoyé: {msg}")
            print(f"distance total : {self.distance}")
            self.iteration = 0
            self.distance_pub.publish(msg)
            self.distance = 0.0
            #rclpy.shutdown()

    def listener_callback(self, msg: Package, nodeROS):
        #Tab_String = str(msg.data).split(",")
        #self.id_colis = Tab_String[0]
        #point1 = Tab_String[1]
        #point2 = Tab_String[2]
        self.id_colis = msg.id
        point1= msg.departure
        point2=msg.arrival
        #print(point2[1:-1].split(" "))
        #print(point2[1:-1].split(" ")[0])

        pathList=[]
        print(f"waiting_list : {self.waiting_list}")
        for i in range(len(self.waiting_list)):
            path=ComputePathToPose.Goal()
            path.goal = PoseStamped()
            path.start = PoseStamped()
            if i == 0:
                path.use_start = False
            else:
                path.start.pose.position.x = self.waiting_list[i-1].pose.position.x
                path.start.pose.position.y = self.waiting_list[i-1].pose.position.y
                path.start.pose.orientation.w = 1.0
                path.start.header.frame_id = 'map'
                path.start.header.stamp = self.get_clock().now().to_msg()
            path.goal.pose.position.x = self.waiting_list[i].pose.position.x
            path.goal.pose.position.y = self.waiting_list[i].pose.position.y
            path.goal.pose.orientation.w = 1.0
            path.goal.header.frame_id = 'map'
            path.goal.header.stamp = self.get_clock().now().to_msg()
            self.send_goal_future = self.path_client.send_goal_async(path)
            self.send_goal_future.add_done_callback(self.path_response_callback)


        path1=ComputePathToPose.Goal()
        
        
        if len(self.waiting_list) != 0:
            path1.start = PoseStamped()
            path1.use_start = True
            TMP = self.waiting_list[-1]
            path1.start.pose.position.x = self.waiting_list[-1].pose.position.x
            path1.start.pose.position.y = self.waiting_list[-1].pose.position.y
            path1.start.pose.orientation.w = 1.0
        else:
            path1.use_start = False

        path1.goal = PoseStamped()

        path1.goal.pose.position.x = point1.pose.position.x
        path1.goal.pose.position.y = point1.pose.position.y
        path1.goal.pose.orientation.w = 1.0
        pathList.append(path1)
        path2=ComputePathToPose.Goal()
        path2.use_start = True

        path2.start = PoseStamped()
        path2.goal = PoseStamped()

        path2.start.pose.position.x = point1.pose.position.x
        path2.start.pose.position.y = point1.pose.position.y
        path2.start.pose.orientation.w = 1.0

        path2.goal.pose.position.x = point2.pose.position.x
        path2.goal.pose.position.y = point2.pose.position.y
        path2.goal.pose.orientation.w = 1.0
        pathList.append(path2)

        for point in pathList:
            if point.use_start == True:
                point.start.header.frame_id = 'map'
                point.start.header.stamp = self.get_clock().now().to_msg()
            point.goal.header.frame_id = 'map'
            point.goal.header.stamp = self.get_clock().now().to_msg()
            self.send_goal_future = self.path_client.send_goal_async(point)
            self.send_goal_future.add_done_callback(self.path_response_callback)
        #return response #je pense qu'il faut lancer le calcul ici pour la distance 

    def listener_win_bid_callback(self, msg):
        print(msg)
        self.id_colis = msg.id
        point1 = msg.departure
        point2 = msg.arrival
        self.waiting_list.append(point1)
        self.waiting_list.append(point2)
        if self.current_goal is None:
            self.send_navigation_goal(self.waiting_list[0])

    def send_navigation_goal(self, point):
        goal_msg = NavigateToPose.Goal()
        #coord = point.split(" ")[1:-1]
        print(point)
        print(type(point))
        #print(point.split(" "))
        goal_msg.pose.pose.position.x = point.pose.position.x
        goal_msg.pose.pose.position.y = point.pose.position.y
        goal_msg.pose.pose.orientation.w = 1.0
        goal_msg.pose.header.frame_id = 'map'
        goal_msg.pose.header.stamp = self.get_clock().now().to_msg()
        self.current_goal = point
        self.nav_client.send_goal_async(goal_msg).add_done_callback(self.nav_response_callback)
    
    def nav_response_callback(self, future):
        print("point")
        goal_handle = future.result()
        if not goal_handle.accepted:
            self.get_logger().warn("Navigation goal rejected")
            self.current_goal = None
            return
        goal_handle.get_result_async().add_done_callback(self.nav_result_callback)

    def nav_result_callback(self, future):
        result = future.result()
        status = result.status

        if status == 4:  # STATUS_SUCCEEDED
            self.get_logger().info("Robot arrivé à destination ✅")

            if self.waiting_list and self.waiting_list[0] == self.current_goal:
                self.waiting_list.pop(0)   # ✅ ICI ET SEULEMENT ICI

        else:
            self.get_logger().warn(f"Navigation échouée, status={status}")

        self.current_goal = None

        if self.waiting_list:
            self.send_navigation_goal(self.waiting_list[0])


def main(args=None):
    rclpy.init(args=args)
    node = Nav2PathEvaluator()
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == '__main__':
    main()
