#!/usr/bin/python3
import rclpy
from rclpy.node import Node

from multi_robot_larm.msg import  package
from multi_robot_larm.msg import  bid

def main(args=None):
    print("oui")


if __name__ == '__main__':
    main()